AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB stream consumer
Parameters:
  DynamoDBStreamArn:
    Type: String
    Default: arn:aws:dynamodb:eu-west-3:851725170841:table/travel-table/stream/2025-11-12T18:05:28.562
    Description: SSM parameter storing the DynamoDB Stream ARN for Couchbase sync
  CouchbaseHost:
    Type: String
    Default: cb.xxxxxx-au5q3vkk.cloud.couchbase.com
    Description: Capella url or self managed node's hostname
  CouchbaseBucket:
    Type: String
    Default: travel-sample
    Description: Couchbase bucket name
  CouchbaseScope:
    Type: String
    Default: _default
    Description: Couchbase scope name
  CouchbaseCollection:
    Type: String
    Default: _default
    Description: Couchbase collection name
  CouchbaseUsername:
    Type: String
    Default: migration-user
    Description: Couchbase username
  CouchbasePassword:
    Type: String
    NoEcho: true
    Description: Couchbase password
Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
    - x86_64
    Timeout: 60
    MemorySize: 256
    LoggingConfig:
      LogFormat: JSON
Resources:
  StreamDLQ:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
    Metadata:
      SamResourceId: StreamDLQ
  DynamoDBToCouchbaseOnlineSync:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler/main.handler
      Policies:
      - AWSLambdaDynamoDBExecutionRole
      - SQSSendMessagePolicy:
          QueueName:
            Fn::GetAtt:
            - StreamDLQ
            - QueueName
      Environment:
        Variables:
          COUCHBASE_HOST:
            Ref: CouchbaseHost
          COUCHBASE_BUCKET:
            Ref: CouchbaseBucket
          COUCHBASE_SCOPE:
            Ref: CouchbaseScope
          COUCHBASE_COLLECTION:
            Ref: CouchbaseCollection
          COUCHBASE_USERNAME:
            Ref: CouchbaseUsername
          COUCHBASE_PASSWORD:
            Ref: CouchbasePassword
      Events:
        FromDynamoDB:
          Type: DynamoDB
          Properties:
            Stream:
              Ref: DynamoDBStreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 1
            MaximumRetryAttempts: 4
            DestinationConfig:
              OnFailure:
                Destination:
                  Fn::GetAtt:
                  - StreamDLQ
                  - Arn
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-zfkk7qtokbkd/573d739ebf0acfb71edd3a7877cd35d6
    Metadata:
      SamResourceId: DynamoDBToCouchbaseOnlineSync
Metadata:
  AWS::ServerlessRepo::Application:
    Name: DynamoDB-online-sync-to-Couchbase
    Description: migrate or sync data from Dynamodb to couchbase
    Author: Hatim HEFFOUDHI
    SpdxLicenseId: MIT
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-zfkk7qtokbkd/86d3f3a95c324c9479bd8986968f4327
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-zfkk7qtokbkd/4d100055b1077c47fd675ec2061d4c5c
    Labels:
    - lambda
    - couchbase
    - sync
    - migrate
    - online
    - blueprint
    - dynamodb
    - sam
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/hatim-heffoudhi/online-sync-dynamodb-to-couchbase
